# Generated by Django 5.2.5 on 2025-09-03 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('csv', 'CSV Data'), ('sql', 'SQL Database'), ('db', 'SQLite Database'), ('sqlite', 'SQLite Database'), ('sqlite3', 'SQLite Database')], max_length=10)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('file_id', models.PositiveIntegerField(help_text='Unique ID for agent processing', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether file is available to agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_message', models.TextField()),
                ('agent_response', models.TextField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='List of tools used in response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='User rating 1-5', null=True)),
                ('user_feedback', models.TextField(blank=True, help_text='User feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('files_referenced', models.ManyToManyField(blank=True, help_text='Files referenced in conversation', to='qna_app.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_session_timeout', models.PositiveIntegerField(default=3600, help_text='Session timeout in seconds')),
                ('max_files_per_user', models.PositiveIntegerField(default=10, help_text='Maximum files per user')),
                ('enable_conversation_history', models.BooleanField(default=True)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('total_files_uploaded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'status'], name='qna_app_upl_user_id_86aec9_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['file_id'], name='qna_app_upl_file_id_e01c96_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'session_id'], name='qna_app_con_user_id_06c363_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='qna_app_con_created_c5fcb3_idx'),
        ),
    ]
