- hosts: webserver
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Install Git
      apt:
        name: git
        state: present
