# Generated by Django 5.2.5 on 2025-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
