# configs/tools_config.yml

# --- Primary Agent Settings ---
# These settings apply to the main LLM that decides which tool to use.
primary_agent:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1

# --- Internet Search Settings ---
tavily_search_api:
  tavily_search_max_results: 5
  search_depth: "advanced"     # basic, advanced
  include_answer: true         # Include AI-generated answers
  include_raw_content: false   # Exclude HTML content

# Optional: Different settings for different environments
environments:
  development:
    primary_agent:
      llm: "gpt-3.5-turbo"  # Cheaper for dev
  production:
    primary_agent:
      llm: "gpt-4o-mini"    # Better quality for prod

# Optional: Configuration constraints
limits:
  max_chunk_size: 4000
  max_overlap_ratio: 0.5
  max_retrieval_k: 20
  max_search_results: 10


# --- PDF RAG Settings ---
# Enhanced version with additional options
pdf_rag:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1
  embedding_model: "text-embedding-3-small"
  chunk_size: 1000
  chunk_overlap: 200
  k: 5
  max_tokens: 1000  # Response length limit
  timeout: 30       # Query timeout in seconds

# --- CSV RAG Settings ---
# These are used by the csv_rag_tool to process documents.
csv_rag:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1
  embedding_model: "text-embedding-3-small"
  chunk_size: 1000
  chunk_overlap: 200
  k: 5 # Number of documents to retrieve for RAG

# --- SQL Tool Settings ---
# These are used by the sql_tool to generate and execute queries.
sql:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1

  