# configs/tools_config.yml

# --- Primary Agent Settings ---
# These settings apply to the main LLM that decides which tool to use.
primary_agent:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1

# --- Internet Search Settings ---
# Tavily API key is loaded from the .env file.
tavily_search_api:
  tavily_search_max_results: 5

# --- PDF RAG Settings ---
# These are used by the pdf_rag_tool to process documents.
pdf_rag:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1
  embedding_model: "text-embedding-3-small"
  chunk_size: 1000
  chunk_overlap: 200
  k: 5 # Number of documents to retrieve for RAG

# --- CSV RAG Settings ---
# These are used by the csv_rag_tool to process documents.
csv_rag:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1
  embedding_model: "text-embedding-3-small"
  chunk_size: 1000
  chunk_overlap: 200
  k: 5 # Number of documents to retrieve for RAG

# --- SQL Tool Settings ---
# These are used by the sql_tool to generate and execute queries.
sql:
  llm: "gpt-4o-mini"
  llm_temperature: 0.1